source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-reloader', require: 'sinatra/reloader'
gem 'activerecord', require: 'active_record'
gem 'sqlite3'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'rack'
gem 'rackup'
gem 'puma'